name: docker image push

on:
  push:
    branches: [ main ]

jobs:
  Run-npm-on-Ubuntu:
    name: Run npm on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: build image
        uses: actions/checkout@v5
      - name: set up JDK 1.8
        uses: actions/setup-java@v5
        with:
         java-version: 1.8  

      - name: grant execute permissions
        run: chmod +x gradlew

      - name: build with gradle
        run: ./gradlew build

      - name: build and push docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
         image: bn2021shashi/2023
         tags: v1, latest
         registry: docker.io
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}
